[package]
name = "api-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.0", features = ["full"] }
web3 = { version = "0.17", features = ["http"] }
ring = "0.16"
serde_json = "1.0"
